<?php

use Illuminate\Database\Seeder;

class HotelDataFromHotelBedsAPISeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        /*
         * maxbiocca
         *
         * APITUDE HOTEL SANDBOX: EVALUATION
         * Key: jty66efkhnfsgwm9qjymbzdk
         * Secret: kre9gM2JRc
         *
         *
         * sayyid
         *
         * APITUDE HOTEL SANDBOX: EVALUATION
         *
         * KEY: cas4sspjfdd5q26mrdqcb2f2
         * SECRET: BggxnudsTR
         *
         *
         * hasanabbax
         *
         * APITUDE HOTEL SANDBOX: EVALUATION
         *
         * KEY: pysddg44tcryeh6q4gfskn5h
         * Secret: qC6mp7f5tT
         *
         *
         * unbeatabil
         *
         * APITUDE HOTEL SANDBOX: EVALUATION
         *
         * KEY: jvxyerr46hfhtsj3zd9ygeej
         * SECRET: tUxTkuRA5U
         *
         * haasan
         *
         * APITUDE HOTEL SANDBOX: EVALUATION
         *
         * KEY: 26wcxgn9j4kyvvhkexuqk3y8
         * SECRET: ZUAcMNcncd
         *
         */

        $apiArray = Array(
            array("jvxyerr46hfhtsj3zd9ygeej", "tUxTkuRA5U"), //OK 3
            array("jty66efkhnfsgwm9qjymbzdk", "kre9gM2JRc"), //OK
            array("cas4sspjfdd5q26mrdqcb2f2", "BggxnudsTR"), //OK
            array("pysddg44tcryeh6q4gfskn5h", "qC6mp7f5tT"), //OK
            array("26wcxgn9j4kyvvhkexuqk3y8", "ZUAcMNcncd") // new
        );

        $i = 0;
        $k = 0; //5places
        $second = 1;

        for ($j = 1; $j <= 250; $j++) {

            if ($second % 49000 == 0) {
                $k++;
            }

            // Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
            $signature = hash("sha256", $apiArray[$k][0] . $apiArray[$k][1] . time());

            $i++;

            if ($i == 1) {
                $first = $i;
            } else {
                $first = $second + 1;
            }

            $second = $i * 1000;

            $endpoint = "https://api.test.hotelbeds.com/hotel-content-api/1.0/hotels?fields=all&language=ENG&from=$first&to=$second";

            echo $endpoint . ' key:' . $apiArray[$k][0] . ' secret:' . $apiArray[$k][1] . "\n <br/>";


            sleep(2);

            // Example of call to the API
            try {
                // Get cURL resource
                $curl = curl_init();
                // Set some options
                curl_setopt_array($curl, array(
                    CURLOPT_RETURNTRANSFER => 1,
                    CURLOPT_URL => $endpoint,
                    CURLOPT_HTTPHEADER => ['Accept:application/json', 'Api-key:' . $apiArray[$k][0] . '', 'X-Signature:' . $signature . '']
                ));
                // Send the request & save response to $resp
                $resp = curl_exec($curl);

                // Check HTTP status code
                if (!curl_errno($curl)) {
                    switch ($http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE)) {
                        case 200:  # OK
                            //                        echo "Server JSON Response:" . $resp;
                            $response = (json_decode($resp));
                            break;
                        default:
                            echo 'Unexpected HTTP code: ', $http_code, "\n";
                            echo $resp;
                    }
                }

                // Close request to clear up some resources
                curl_close($curl);


            } catch (Exception $ex) {

                printf("Error while sending request, reason: %s\n", $ex->getMessage());

            }

            foreach ($response->hotels as $instance) {
                DB::table('hotel_beds_test')->insert([
                    'all_data' => gzcompress(serialize($instance)),
                    'name' => (isset($instance->name->content) ? $instance->name->content : 'Not Available'),
                    'country_code' => (isset($instance->countryCode) ? $instance->countryCode : 'Not Available'),
                    'destination_code' => (isset($instance->destinationCode) ? $instance->destinationCode : 'Not Available'),
                    'address' => (isset($instance->address->content) ? $instance->address->content : 'Not Available'),
                    'city' => (isset($instance->city->content) ? $instance->city->content : 'Not Available'),
                    'postal_code' => (isset($instance->postalCode) ? $instance->postalCode : 'Not Available'),
                    'website' => (isset($instance->web) ? $instance->web : 'Not Available'),
                    'created_at' => DB::raw('now()'),
                    'updated_at' => DB::raw('now()')
                ]);
            }

        }

    }
}
