<?php

use Illuminate\Database\Seeder;

class GatheringCountriesDataFromHotelBedsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        /*
         * APITUDE for Activities Sandbox: APITUDE for Activities Evaluation
         * Key: gj35y5vtnqc38znqmmmrad3k
         * Secret: jURav9VUbz
         *
         * APITUDE Hotel Sandbox: Evaluation
         * Key: jty66efkhnfsgwm9qjymbzdk
         * Secret: kre9gM2JRc
         */
// Your API Key and secret
        $apiKey = "jty66efkhnfsgwm9qjymbzdk";
        $Secret = "kre9gM2JRc";

// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
        $signature = hash("sha256", $apiKey . $Secret . time());

        $endpoint = "https://api.test.hotelbeds.com/hotel-content-api/1.0/locations/countries?fields=all&language=ENG&from=1&to=300";

        echo "Your API Key is: " . $apiKey . "";
        echo "Your X-Signature is: " . $signature . "";

// Example of call to the API
        try {
            // Get cURL resource
            $curl = curl_init();
            // Set some options
            curl_setopt_array($curl, array(
                CURLOPT_RETURNTRANSFER => 1,
                CURLOPT_URL => $endpoint,
                CURLOPT_HTTPHEADER => ['Accept:application/json', 'Api-key:' . $apiKey . '', 'X-Signature:' . $signature . '']
            ));
            // Send the request & save response to $resp
            $resp = curl_exec($curl);

            // Check HTTP status code
            if (!curl_errno($curl)) {
                switch ($http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE)) {
                    case 200:  # OK
//                        echo "Server JSON Response:" . $resp;
                        $response = (json_decode($resp));
                        break;
                    default:
                        echo 'Unexpected HTTP code: ', $http_code, "\n";
                        echo $resp;
                }
            }

            // Close request to clear up some resources
            curl_close($curl);


        } catch (Exception $ex) {

            printf("Error while sending request, reason: %s\n", $ex->getMessage());

        }
        $i = 0;
        foreach ($response->countries as $instance) {
            DB::table('countries')->insert([
                'uid' => uniqid(),
                's_no' => ++$i,
                'country_code' => $instance->code,
                'iso_code' => $instance->isoCode,
                'name' => $instance->description->content,
                'number_of_states' => count($instance->states),
                'states' => serialize($instance->states),
                'all_data' => serialize($instance),
                'source' => 'developer.hotelbeds.com',
                'created_at' => DB::raw('now()'),
                'updated_at' => DB::raw('now()')
            ]);
        }
    }
}
